"""empty message

Revision ID: 37d1df555cc1
Revises: 560bf6799a90
Create Date: 2023-03-29 23:41:24.629202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d1df555cc1'
down_revision = '560bf6799a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Date(), nullable=False))
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
