"""empty message

Revision ID: 5c8bd1c81de7
Revises: 186aaa787d29
Create Date: 2023-03-28 23:44:34.925205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8bd1c81de7'
down_revision = '186aaa787d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.drop_column('searching_for_venue')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=False))
        batch_op.drop_column('searching_for_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searching_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_talent')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searching_for_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
